site_name: Organic
site_description: Documentation for the Organic image reconstruction package.
site_author: Toon De Prins
site_url: https://organic.readthedocs.io/en/latest/

# Github repo information.
repo_url: https://github.com/DePrinsT/organic
repo_name: DePrinsT/organic

# Don't complete build with warnings.
strict: true

theme:
  name: material
  logo: "assets/organic_logo.png"
  features:
      - navigation.sections  # Sections are included in the navigation on the left.
      - toc.integrate  # Table of contents is integrated on the left; does not appear separately on the right.
      - header.autohide  # Header disappears as you scroll.
      - content.code.copy
  palette:
      # Light mode / dark mode
      - scheme: default
        primary: black
        accent: amber
        toggle:
            icon: material/weather-night
            name: Switch to dark mode
      - scheme: slate
        primary: black
        accent: amber
        toggle:
            icon: material/weather-sunny
            name: Switch to light mode


extra_css:
    - stylesheets/custom_style.css